esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}

network:
  enable_ipv6: true
    
# WiFi connection
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  ap:
    ssid: ${devicename}_fallback
    password: ${wifi_password}
    ap_timeout: 1min
  use_address: ${devicename}.local
  min_auth_mode: WPA2

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: ${api_encryption_key}

# Enable over-the-air updates
ota:
  platform: esphome
  password: ${ota_password}

# Enable Web server
#web_server:
#  port: 80

time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information
text_sensor:
  - platform: version
    name: Version
    disabled_by_default: True
  - platform: wifi_info
#    id: wifi_info
    ip_address:
      name: IP Address

switch:
  # Switch to restart the plug
  - platform: restart
    name: Restart Switch
    disabled_by_default: True

sensor:
  - platform: uptime
    name: Uptime
    disabled_by_default: True

