esphome:
  comment: "Gosund SP1 - Light"

# Binary sensor for the power button
binary_sensor:
  - platform: gpio
    name: Button
    id: button
    pin:
      number: GPIO3
      inverted: true
    on_press:
      - light.toggle: lightid
    disabled_by_default: True

light:
  - platform: binary
    id: lightid
    output: relay
    name: Licht
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led
