esphome:
  comment: "Hama Plug"

esp8266:
  board: esp8285

sensor:
  # Gosund SP1 Config
  # Power sensor
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current_resistor: "0.00204"
    voltage_divider: "719"
    update_interval: 10s
    # Current sensor
    current:
      name: Stromstaerke
      unit_of_measurement: A
      accuracy_decimals: 2
      disabled_by_default: True
    # Voltage sensor
    voltage:
      name: Spannung
      unit_of_measurement: V
      accuracy_decimals: 1
      disabled_by_default: True
    # Power sensor
    power:
      id: power
      name: Leistung
      unit_of_measurement: W
      accuracy_decimals: 0
  # Total daily energy sensor
  - platform: total_daily_energy
    name: Tagesleistung
    power_id: power
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh

# Binary sensor for the power button
binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO3
      inverted: true
    on_press:
      - switch.toggle: switchid
    disabled_by_default: True

switch:
  - platform: gpio
    name: Bewässerung
    pin: GPIO14
    id: switchid
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - delay: 30m
      - switch.turn_off: switchid

output:
  # esphome state led
  - platform: esp8266_pwm
    id: state_led
    pin:
      number: GPIO1
      inverted: true

light:
  # Power state light
  - platform: monochromatic
    output: state_led
    id: led
    disabled_by_default: True


# Uses the red LED as a status indicator
status_led:
  pin:
    number: GPIO13
    inverted: true
