substitutions:
  max_power: "3700"
  max_temp: "85.0"

esphome:
  comment: "Shelly Plus 1PM"
  platformio_options:
    board_build.f_cpu: 160000000L

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"

binary_sensor:
  - platform: gpio
    name: "Switch"
    pin: GPIO4
    on_state:
      then:
        - light.toggle: relay
    filters:
      - delayed_on_off: 50ms
    disabled_by_default: True

output:
  - platform: gpio
    pin: GPIO26
    id: relay_out

light:
  - platform: binary
    name: Licht
    output: relay_out
    restore_mode: RESTORE_DEFAULT_OFF
    id: relay

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: Temperatur
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: ${max_temp}
        then:
          - light.turn_off: "relay"
          - homeassistant.service:
              service: persistent_notification.create
              data:
                title: Message from ${friendly_name}
              data_template:
                message: Light ${friendly_name} turned off because power exceeded ${max_temp} °C
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: adc
    id: temp_analog_reading
    pin: GPIO32
    attenuation: 12db
    disabled_by_default: True
  - platform: adc
    name: "Versorgungsspannung Relais"
    pin: GPIO33
    attenuation: 12db
    filters:
      - multiply: 8
    disabled_by_default: True
  - platform: hlw8012
    model: BL0937
    sel_pin:
      number: GPIO23
      inverted: true
    cf_pin: GPIO5
    cf1_pin: GPIO18
    current_resistor: "0.001"
    voltage_divider: "1925"
    current:
      name: "Stromstaerke"
      unit_of_measurement: A
      accuracy_decimals: 3
      icon: mdi:flash-outline
      disabled_by_default: True
    voltage:
      name: "Spannung"
      unit_of_measurement: V
      accuracy_decimals: 1
      icon: mdi:flash-outline
      disabled_by_default: True
    power:
      name: "Leistung"
      unit_of_measurement: W
      id: power
      icon: mdi:flash-outline
      on_value_range:
        - above: ${max_power}
          then:
            - light.turn_off: "relay"
            - homeassistant.service:
                service: persistent_notification.create
                data:
                  title: Message from ${friendly_name}
                data_template:
                  message: Light ${friendly_name} turned off because power exceeded ${max_power}W
    change_mode_every: 2
    update_interval: 10s
  - platform: total_daily_energy
    name: "Tagesleistung"
    power_id: power
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    icon: mdi:clock-alert
