esphome:
  comment: "Shelly 1 Mini Gen3"

esp32:
  board: esp32-c3-devkitm-1
  flash_size: 8MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: "Temperatur"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
    disabled_by_default: True
  - platform: adc
    id: temp_analog_reading
    pin: GPIO3
    attenuation: 12db
    disabled_by_default: True

output:
  - platform: gpio
    id: "relay_output"
    pin: 7

switch:
  - platform: output
    id: "relay"
    name: "Relay"
    output: "relay_output"
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    name: "Schalter"
    pin: 10
    on_state:
      then:
        - switch.toggle: "relay"
    filters:
      - delayed_on_off: 50ms
    disabled_by_default: True

#  - platform: gpio
#    name: "Button"
#    pin:
#      number: 1
#      inverted: yes
#      mode:
#        input: true
#        pullup: true
#
#status_led:
#  pin:
#    number: 0
#    inverted: true
