esphome:
  comment: "Shelly Dimmer 2"

esp8266:
  board: esp8285

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 115200

light:
  # Dimmer.
  - platform: shelly_dimmer
    name: Licht
    id: thislight
    power:
      name: Leistung
      id: power
    voltage:
      name: Spannung
      disabled_by_default: True
    current:
      name: Stromstaerke
      disabled_by_default: True
    min_brightness: ${min_brightness}
    max_brightness: ${max_brightness}
    firmware:
      version: "51.6"
    restore_mode: RESTORE_DEFAULT_OFF
    #  - platform: binary
    #    name: "${friendly_name} RESET SHD"
    #    output: SHDReset

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: Temperatur
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
    disabled_by_default: True
  - platform: adc
    id: temp_analog_reading
    pin: A0
    disabled_by_default: True
  - platform: adc
    pin: VCC
    name: "VCC"
    disabled_by_default: True

  # Total daily energy sensor
  - platform: total_daily_energy
    name: Tagesleistung
    power_id: power
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
    name: Switch
    disabled_by_default: True
    filters:
      - delayed_on_off: 100ms
    on_release:
      then:
        - light.toggle: thislight
